import { useTranslations } from 'next-intl'
import React from 'react'

export default function PrivacyPolicy () {
  const t = useTranslations('privacy-policy')
  return (
    <div className='flex flex-col gap-4 justify-start pb-[6.25rem]'>
      <h1 className='w-full text-5xl md:text-7xl text-it-blue-1 font-extrabold px-2 text-left md:text-center'>
        {t('title')}
      </h1>
      <section className='w-full px-3 flex flex-col justify-start items-center'>
        <p className='w-full text-2xl font-normal text-it-gray-2 text-left md:text-justify md:max-w-prose'>
          Lorem ipsum dolor sit amet consectetur. Tristique eleifend molestie nibh velit neque aliquam duis donec sed. Bibendum quis sapien sollicitudin in nullam porttitor interdum. Vulputate pulvinar vulputate bibendum nisl varius ipsum enim pharetra. Fermentum ipsum diam cras turpis eget duis et. Vitae viverra lobortis amet id amet libero interdum. Interdum blandit orci cras purus vitae varius gravida. A phasellus adipiscing praesent nec in nisi sagittis tempor at. Adipiscing vel at et gravida leo nullam ac enim donec. Sed urna commodo nec vel elementum ac ac orci.
          In est enim metus neque hendrerit. Fringilla rhoncus pellentesque sem libero lorem a. Feugiat sed lectus pellentesque semper adipiscing lacus malesuada sed tempor. Ac pretium diam nisl et urna in cursus. Ac est felis dictum elementum in felis tempus cras consequat. Egestas risus pellentesque egestas dapibus. Gravida mattis nibh in convallis. Tortor lacus morbi odio sed ridiculus et turpis. Tempus mi magna euismod at velit elementum. Lectus tortor sollicitudin blandit nibh sed dolor non. Id quis ligula nulla massa mauris ac sit gravida tincidunt. Quis purus sagittis augue consectetur sed vulputate facilisis. Velit amet magnis placerat eget ac id.
          Ut vitae quis odio mattis justo cursus gravida. Habitant lobortis et in id. Enim faucibus sed gravida lectus praesent integer consectetur placerat luctus. Sed ac a turpis tempor porta egestas tellus diam. Senectus velit et sed donec mus augue porta nunc eget.
          Sit sed ultrices pellentesque ante condimentum suspendisse volutpat. Vel quam egestas quam nulla mi fermentum amet est pretium. Amet in morbi cursus dignissim maecenas. Diam porta volutpat tempor quam euismod vestibulum pellentesque vitae eros. Porttitor consectetur molestie nunc purus nec tincidunt ac. At pretium tellus integer bibendum mus.
          Volutpat at massa scelerisque diam elementum purus. Sit in lectus nunc viverra imperdiet est convallis ut tellus. Ut nunc urna imperdiet cum lorem. Aenean augue sed accumsan ac viverra at vitae justo. Etiam molestie leo ac dolor lorem quam fermentum. Maecenas pulvinar est id facilisis. Vitae lorem sit vel quam volutpat aliquam eu ultrices. Dui ut semper consectetur ut. Nibh bibendum amet ipsum facilisis. Eget vitae morbi sed odio dignissim morbi. Ornare aliquet vulputate facilisi in quis pulvinar vestibulum egestas. Libero dui turpis velit lacus at mauris facilisi leo orci. Vitae risus cursus imperdiet tristique volutpat ipsum nibh.
          Eros vulputate at tincidunt massa mauris quam amet. At eget adipiscing mauris in. Scelerisque tempus quis fames laoreet imperdiet. Quis faucibus id egestas erat a augue praesent. Consectetur viverra enim nibh vel sit tellus pellentesque consequat velit. Tellus lacus posuere felis euismod eget sed. Cras velit porttitor tincidunt sit in aenean egestas. Etiam feugiat dictum tempor in eget amet.
          Gravida arcu sed sed purus quam sed ornare. Venenatis gravida sed est scelerisque imperdiet sollicitudin. In sit ultricies tortor duis. Viverra ut posuere et turpis duis sit pellentesque morbi. Ultrices vestibulum pellentesque at sit. Ultrices odio facilisi ac eleifend in. At in malesuada varius commodo in vestibulum. Ut hendrerit ut pellentesque mus fermentum. Morbi viverra risus euismod semper etiam. Id purus nisl purus nunc non sed commodo massa. Velit diam tellus augue in. Placerat sed at quisque cursus nunc.
          Amet leo in turpis duis. Pulvinar elit quis aliquam dapibus volutpat ornare. Tristique vitae nunc magna elit blandit nibh. Magna volutpat turpis amet volutpat vitae eu etiam eu. Vivamus lacus nascetur sodales scelerisque. Viverra pretium dignissim viverra eget malesuada eget a enim. Laoreet et enim nunc malesuada habitant. A sem sapien integer dictum eget adipiscing. Hendrerit neque tempor imperdiet lorem. Augue elementum quisque nec donec netus etiam integer phasellus. Porta turpis mus ut nunc integer. Malesuada sem imperdiet a mi nisl malesuada bibendum eu eleifend. Elit ultricies nulla sed sociis.
          Ac faucibus id et praesent vel est dictum mi. Orci sit sit tortor cursus. Sem nunc quis lorem enim sed donec faucibus. Sed venenatis feugiat dignissim maecenas lectus sodales. Egestas viverra semper risus amet nibh euismod. Tellus tellus urna egestas donec tristique leo at risus donec. Ornare odio gravida amet duis ridiculus.
          Molestie ut egestas metus facilisis faucibus. Urna egestas nisl non bibendum eu et. Tristique nibh egestas aliquam et in. Maecenas donec nisl aliquam sem amet hendrerit turpis et. Netus etiam amet penatibus id condimentum eu.
          Ornare adipiscing commodo id gravida posuere gravida sapien varius euismod. Sed malesuada pulvinar diam viverra eget vestibulum commodo. Vitae hendrerit nec ultrices consequat ultricies urna. Commodo venenatis tincidunt accumsan accumsan cras. Risus aliquam tincidunt et morbi.
          Consequat egestas cras id in sit ac tristique morbi. Pretium tempor non nulla augue pellentesque. Augue lobortis ullamcorper cras dolor magna augue. Risus odio euismod metus magna vulputate sit. Nisi orci sed mauris dui. Congue aliquam commodo elementum ornare cras quis. Turpis felis sagittis laoreet natoque felis ac.
          Proin aliquam tincidunt faucibus fusce et nam. Tincidunt et curabitur aliquet a a risus porttitor. Purus nisi malesuada curabitur tincidunt ut. Id commodo vitae auctor consectetur nisl fringilla lacus quis. Ornare magna non sit scelerisque malesuada. Gravida commodo faucibus ut sit mi pellentesque fringilla. Orci mauris pellentesque egestas massa. Duis sit viverra placerat eget felis. Gravida eu turpis mattis tincidunt est faucibus. Tincidunt et amet lectus adipiscing volutpat sit eget dignissim nec. Amet ornare risus aliquam donec fringilla vulputate. Nec scelerisque sed egestas purus massa egestas tristique. Id aliquet vestibulum at molestie et fermentum id. Ut diam nulla eu vel risus est curabitur. Id ut pharetra faucibus feugiat dignissim in.
          Ut sed libero morbi tellus mauris montes ultricies felis. Egestas quis praesent odio dui. Phasellus lectus nulla porttitor elementum nam mauris. Morbi et fringilla ac eget amet pretium bibendum lacus. Eu nisl est morbi sed et placerat mattis in. Sit nulla aliquam sit tincidunt pretium a. Rhoncus tortor risus purus commodo feugiat nec ultricies. Eget rhoncus luctus eleifend feugiat pulvinar eget justo consectetur.
          Proin diam amet senectus cursus odio vitae nisl in magna. Habitasse vel ullamcorper cursus nulla aliquet. Fames adipiscing elementum sem eu placerat sed. Suscipit interdum condimentum sit in enim. Scelerisque feugiat pretium ut ultricies at convallis ornare. Ut senectus odio tempus consequat convallis. Lobortis viverra ut tempus amet in eget euismod maecenas tristique. Augue sed amet integer amet lectus commodo a ut. Non fames congue id tempor eu et proin velit porta. In a cursus et metus neque proin semper dolor. Dis porttitor at lobortis magna tincidunt.
          Sit enim odio mauris pharetra nunc. Varius donec ac euismod vitae et amet. Id non turpis bibendum quam lectus tempus. Orci purus cursus a nunc auctor vitae at viverra id. Tristique enim amet dapibus duis cursus. In in tellus faucibus commodo sem nulla amet laoreet. Vitae velit eu urna blandit ut quis mauris bibendum donec. Sit sit sapien ut eget ac fermentum eu eget. Semper quam turpis et congue tincidunt velit orci viverra. Sit eu velit risus posuere. Purus eu mi egestas mauris. Vitae.
        </p>
      </section>
    </div>
  )
}
