import { aceh } from '@/styles/aceh-font'
import './globals.css'

export const metadata = {
  title: 'IT-mobile',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en' data-theme='corporate'>
      <body className={`${aceh.variable} font-aceh`}>
        {children}
      </body>
    </html>
  )
}
